

HASH_PARAMETERS struct

	ADLER32parameterA dd ?
	CRC16parameterA dd ?
	CRC16CCITTparameterA dd ?
	CRC32parameterA dd ?
	CRC32bparameterA dd ?

	GOSTparameterA dd ?
	GOSTparameterB dd ?
	GOSTparameterC dd ?
	GOSTparameterD dd ?
	GOSTparameterE dd ?
	GOSTparameterF dd ?
	GOSTparameterG dd ?
	GOSTparameterH dd ?

	HAVALparameterA dd ?
	HAVALparameterB dd ?
	HAVALparameterC dd ?
	HAVALparameterD dd ?
	HAVALparameterE dd ?
	HAVALparameterF dd ?
	HAVALparameterG dd ?
	HAVALparameterH dd ?

	MD4parameterA dd ?
	MD4parameterB dd ?
	MD4parameterC dd ?
	MD4parameterD dd ?

	MD5parameterA dd ?
	MD5parameterB dd ?
	MD5parameterC dd ?
	MD5parameterD dd ?

	PANAMAparameterA dd ?
	PANAMAparameterB dd ?
	PANAMAparameterC dd ?
	PANAMAparameterD dd ?
	PANAMAparameterE dd ?
	PANAMAparameterF dd ?
	PANAMAparameterG dd ?
	PANAMAparameterH dd ?

	RIPE128parameterA dd ?
	RIPE128parameterB dd ?
	RIPE128parameterC dd ?
	RIPE128parameterD dd ?

	RIPE160parameterA dd ?
	RIPE160parameterB dd ?
	RIPE160parameterC dd ?
	RIPE160parameterD dd ?
	RIPE160parameterE dd ?

	RIPE256parameterA dd ?
	RIPE256parameterB dd ?
	RIPE256parameterC dd ?
	RIPE256parameterD dd ?
	RIPE256parameterE dd ?
	RIPE256parameterF dd ?
	RIPE256parameterG dd ?
	RIPE256parameterH dd ?

	RIPE320parameterA dd ?
	RIPE320parameterB dd ?
	RIPE320parameterC dd ?
	RIPE320parameterD dd ?
	RIPE320parameterE dd ?
	RIPE320parameterF dd ?
	RIPE320parameterG dd ?
	RIPE320parameterH dd ?
	RIPE320parameterI dd ?
	RIPE320parameterJ dd ?

	SHA0parameterA dd ?
	SHA0parameterB dd ?
	SHA0parameterC dd ?
	SHA0parameterD dd ?
	SHA0parameterE dd ?

	SHA1parameterA dd ?
	SHA1parameterB dd ?
	SHA1parameterC dd ?
	SHA1parameterD dd ?
	SHA1parameterE dd ?

	SHA256parameterA dd ?
	SHA256parameterB dd ?
	SHA256parameterC dd ?
	SHA256parameterD dd ?
	SHA256parameterE dd ?
	SHA256parameterF dd ?
	SHA256parameterG dd ?
	SHA256parameterH dd ?

	SHA384parameterA dd ?
	SHA384parameterB dd ?
	SHA384parameterC dd ?
	SHA384parameterD dd ?
	SHA384parameterE dd ?
	SHA384parameterF dd ?
	SHA384parameterG dd ?
	SHA384parameterH dd ?
	SHA384parameterI dd ?
	SHA384parameterJ dd ?
	SHA384parameterK dd ?
	SHA384parameterL dd ?
	SHA384parameterM dd ?
	SHA384parameterN dd ?
	SHA384parameterO dd ?
	SHA384parameterP dd ?

	SHA512parameterA dd ?
	SHA512parameterB dd ?
	SHA512parameterC dd ?
	SHA512parameterD dd ?
	SHA512parameterE dd ?
	SHA512parameterF dd ?
	SHA512parameterG dd ?
	SHA512parameterH dd ?
	SHA512parameterI dd ?
	SHA512parameterJ dd ?
	SHA512parameterK dd ?
	SHA512parameterL dd ?
	SHA512parameterM dd ?
	SHA512parameterN dd ?
	SHA512parameterO dd ?
	SHA512parameterP dd ?

	SNEFRUparameterA dd ?
	SNEFRUparameterB dd ?
	SNEFRUparameterC dd ?
	SNEFRUparameterD dd ?
	SNEFRUparameterE dd ?
	SNEFRUparameterF dd ?
	SNEFRUparameterG dd ?
	SNEFRUparameterH dd ?

	TIGERparameterA dd ?
	TIGERparameterB dd ?
	TIGERparameterC dd ?
	TIGERparameterD dd ?
	TIGERparameterE dd ?
	TIGERparameterF dd ?

	WHIRLPOOLparameterA dd ?
	WHIRLPOOLparameterB dd ?
	WHIRLPOOLparameterC dd ?
	WHIRLPOOLparameterD dd ?
	WHIRLPOOLparameterE dd ?
	WHIRLPOOLparameterF dd ?
	WHIRLPOOLparameterG dd ?
	WHIRLPOOLparameterH dd ?
	WHIRLPOOLparameterI dd ?
	WHIRLPOOLparameterJ dd ?
	WHIRLPOOLparameterK dd ?
	WHIRLPOOLparameterL dd ?
	WHIRLPOOLparameterM dd ?
	WHIRLPOOLparameterN dd ?
	WHIRLPOOLparameterO dd ?
	WHIRLPOOLparameterP dd ?
	WHIRLPOOLparameterQ dd ?
	WHIRLPOOLparameterR dd ?
	WHIRLPOOLparameterS dd ?
	WHIRLPOOLparameterT dd ?

HASH_PARAMETERS ends
